theme: jekyll-theme-minimal
titel: Max's Private  Space
description: This  is Max's very first web! Weccome to here!
lsi: false
safe: true
source: runningboy-coder.github.io
incremental : false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine :mathjax
  syntax_highlighter :rouge
